/********************************************************************
* NKNFADC400Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NKNFADC400Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNKNFADC400Dict();
extern void G__cpp_setup_inheritanceNKNFADC400Dict();
extern void G__cpp_setup_typetableNKNFADC400Dict();
extern void G__cpp_setup_memvarNKNFADC400Dict();
extern void G__cpp_setup_globalNKNFADC400Dict();
extern void G__cpp_setup_memfuncNKNFADC400Dict();
extern void G__cpp_setup_funcNKNFADC400Dict();
extern void G__set_cpp_environmentNKNFADC400Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NKNFADC400.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NKNFADC400DictLN_TClass;
extern G__linked_taginfo G__NKNFADC400DictLN_TBuffer;
extern G__linked_taginfo G__NKNFADC400DictLN_TMemberInspector;
extern G__linked_taginfo G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NKNFADC400DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NKNFADC400DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NKNFADC400DictLN_NK6UVME;
extern G__linked_taginfo G__NKNFADC400DictLN_NKNFADC400;

/* STUB derived class for protected member access */
