//
// File generated by rootcint at Fri Feb  3 13:27:10 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NKNFADC400Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NKNFADC400Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void NKNFADC400_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NKNFADC400(void *p = 0);
   static void *newArray_NKNFADC400(Long_t size, void *p);
   static void delete_NKNFADC400(void *p);
   static void deleteArray_NKNFADC400(void *p);
   static void destruct_NKNFADC400(void *p);
   static void streamer_NKNFADC400(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::NKNFADC400*)
   {
      ::NKNFADC400 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NKNFADC400 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NKNFADC400", ::NKNFADC400::Class_Version(), "NoticeNFADC400.h", 4,
                  typeid(::NKNFADC400), ::ROOT::DefineBehavior(ptr, ptr),
                  &::NKNFADC400::Dictionary, isa_proxy, 0,
                  sizeof(::NKNFADC400) );
      instance.SetNew(&new_NKNFADC400);
      instance.SetNewArray(&newArray_NKNFADC400);
      instance.SetDelete(&delete_NKNFADC400);
      instance.SetDeleteArray(&deleteArray_NKNFADC400);
      instance.SetDestructor(&destruct_NKNFADC400);
      instance.SetStreamerFunc(&streamer_NKNFADC400);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::NKNFADC400*)
   {
      return GenerateInitInstanceLocal((::NKNFADC400*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NKNFADC400*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr NKNFADC400::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *NKNFADC400::Class_Name()
{
   return "NKNFADC400";
}

//______________________________________________________________________________
const char *NKNFADC400::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKNFADC400*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NKNFADC400::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKNFADC400*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NKNFADC400::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKNFADC400*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NKNFADC400::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKNFADC400*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void NKNFADC400::Streamer(TBuffer &R__b)
{
   // Stream an object of class NKNFADC400.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      NK6UVME::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, NKNFADC400::IsA());
   } else {
      R__c = R__b.WriteVersion(NKNFADC400::IsA(), kTRUE);
      NK6UVME::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void NKNFADC400::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NKNFADC400.
      TClass *R__cl = ::NKNFADC400::IsA();
      if (R__cl || R__insp.IsA()) { }
      NK6UVME::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_NKNFADC400(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::NKNFADC400 : new ::NKNFADC400;
   }
   static void *newArray_NKNFADC400(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::NKNFADC400[nElements] : new ::NKNFADC400[nElements];
   }
   // Wrapper around operator delete
   static void delete_NKNFADC400(void *p) {
      delete ((::NKNFADC400*)p);
   }
   static void deleteArray_NKNFADC400(void *p) {
      delete [] ((::NKNFADC400*)p);
   }
   static void destruct_NKNFADC400(void *p) {
      typedef ::NKNFADC400 current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_NKNFADC400(TBuffer &buf, void *obj) {
      ((::NKNFADC400*)obj)->::NKNFADC400::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::NKNFADC400

/********************************************************
* NKNFADC400Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNKNFADC400Dict();

extern "C" void G__set_cpp_environmentNKNFADC400Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NKNFADC400.h");
  G__cpp_reset_tagtableNKNFADC400Dict();
}
#include <new>
extern "C" int G__cpp_dllrevNKNFADC400Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NKNFADC400 */
static int G__NKNFADC400Dict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKNFADC400* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKNFADC400[n];
     } else {
       p = new((void*) gvp) NKNFADC400[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKNFADC400;
     } else {
       p = new((void*) gvp) NKNFADC400;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400open((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400read_BUFFER((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])
, (unsigned long) G__int(libp->para[4]), (unsigned short*) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400read_TTIME((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])
, (char*) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_TPattern((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400dump_BUFFER((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])
, (unsigned long) G__int(libp->para[4]), (char*) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400dump_TAG((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])
, (unsigned long) G__int(libp->para[4]), (char*) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_DACOFF((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_DACOFF((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400measure_PED((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_PED((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_DACGAIN((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_DACGAIN((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_DLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_DLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->FADC400read_PEDADC((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_POL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_POL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_DT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_DT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_CW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_CW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_TM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_TM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_PCT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_PCT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_PCI((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_PCI((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_PWT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NKNFADC400*) G__getstructoffset())->NFADC400read_PWT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400reset((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_RM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (int) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_RM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400startL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400stopL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_RunL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400startH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400stopH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_RunH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_RL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_RL((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400read_TIMER((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_ENUM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_TLT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_TLT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_TOW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_TOW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400enable_DCE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400disable_DCE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_DCE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_STAT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400check_CPU((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->waitCPU((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400prog_FPGA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400stat_FPGA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400version_FPGA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400prog_CPLD((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400stat_CPLD((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400version_CPLD((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400read_SN((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400enable_FLASH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400disable_FLASH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400check_FLASH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400write_FLASH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned char) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3])
, (unsigned char) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400read_FLASH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKNFADC400*) G__getstructoffset())->NFADC400stat_FLASH((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400update_FPGA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400update_CPLD((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->NFADC400update_ALUT((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (char*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NKNFADC400::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKNFADC400::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NKNFADC400::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NKNFADC400::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKNFADC400*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_80(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKNFADC400::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_81(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKNFADC400::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_82(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKNFADC400::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NKNFADC400Dict_169_0_83(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKNFADC400::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NKNFADC400Dict_169_0_84(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NKNFADC400* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NKNFADC400(*(NKNFADC400*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NKNFADC400 G__TNKNFADC400;
static int G__NKNFADC400Dict_169_0_85(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NKNFADC400*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NKNFADC400*) (soff+(sizeof(NKNFADC400)*i)))->~G__TNKNFADC400();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NKNFADC400*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NKNFADC400*) (soff))->~G__TNKNFADC400();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NKNFADC400Dict_169_0_86(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKNFADC400* dest = (NKNFADC400*) G__getstructoffset();
   *dest = *(NKNFADC400*) libp->para[0].ref;
   const NKNFADC400& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NKNFADC400 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNKNFADC400Dict {
 public:
  G__Sizep2memfuncNKNFADC400Dict(): p(&G__Sizep2memfuncNKNFADC400Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNKNFADC400Dict::*p)();
};

size_t G__get_sizep2memfuncNKNFADC400Dict()
{
  G__Sizep2memfuncNKNFADC400Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNKNFADC400Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400))) {
     NKNFADC400 *G__Lderived;
     G__Lderived=(NKNFADC400*)0x1000;
     {
       NK6UVME *G__Lpbase=(NK6UVME*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400),G__get_linked_tagnum(&G__NKNFADC400DictLN_NK6UVME),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNKNFADC400Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NKNFADC400DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NKNFADC400DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NKNFADC400DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NKNFADC400DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NKNFADC400 */
static void G__setup_memvarNKNFADC400(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400));
   { NKNFADC400 *p; p=(NKNFADC400*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NKNFADC400DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNKNFADC400Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNKNFADC400(void) {
   /* NKNFADC400 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400));
   G__memfunc_setup("NKNFADC400",649,G__NKNFADC400Dict_169_0_1, 105, G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400open",930,G__NKNFADC400Dict_169_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_BUFFER",1445,G__NKNFADC400Dict_169_0_3, 121, -1, -1, 0, 6, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - range "
"k - - 0 - nevt R - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_TTIME",1390,G__NKNFADC400Dict_169_0_4, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - nevt "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_TPattern",1821,G__NKNFADC400Dict_169_0_5, 107, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - nevt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400dump_BUFFER",1471,G__NKNFADC400Dict_169_0_6, 121, -1, -1, 0, 6, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - range "
"k - - 0 - page C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400dump_TAG",1249,G__NKNFADC400Dict_169_0_7, 121, -1, -1, 0, 6, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - range "
"k - - 0 - page C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_DACOFF",1565,G__NKNFADC400Dict_169_0_8, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_DACOFF",1422,G__NKNFADC400Dict_169_0_9, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400measure_PED",1562,G__NKNFADC400Dict_169_0_10, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_PED",1220,G__NKNFADC400Dict_169_0_11, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_DACGAIN",1633,G__NKNFADC400Dict_169_0_12, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_DACGAIN",1490,G__NKNFADC400Dict_169_0_13, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_DLY",1379,G__NKNFADC400Dict_169_0_14, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_DLY",1236,G__NKNFADC400Dict_169_0_15, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FADC400read_PEDADC",1342,G__NKNFADC400Dict_169_0_16, 107, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - adc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_POL",1381,G__NKNFADC400Dict_169_0_17, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_POL",1238,G__NKNFADC400Dict_169_0_18, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_THR",1384,G__NKNFADC400Dict_169_0_19, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_THR",1241,G__NKNFADC400Dict_169_0_20, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_DT",1298,G__NKNFADC400Dict_169_0_21, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_DT",1155,G__NKNFADC400Dict_169_0_22, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_CW",1300,G__NKNFADC400Dict_169_0_23, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_CW",1157,G__NKNFADC400Dict_169_0_24, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_TM",1307,G__NKNFADC400Dict_169_0_25, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch i - - 0 - ew "
"i - - 0 - en", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_TM",1164,G__NKNFADC400Dict_169_0_26, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_PCT",1377,G__NKNFADC400Dict_169_0_27, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_PCT",1234,G__NKNFADC400Dict_169_0_28, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_PCI",1366,G__NKNFADC400Dict_169_0_29, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_PCI",1223,G__NKNFADC400Dict_169_0_30, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_PWT",1397,G__NKNFADC400Dict_169_0_31, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch f - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_PWT",1254,G__NKNFADC400Dict_169_0_32, 102, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400reset",1043,G__NKNFADC400Dict_169_0_33, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_RM",1305,G__NKNFADC400Dict_169_0_34, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"i - - 0 - st i - - 0 - se "
"i - - 0 - sr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_RM",1162,G__NKNFADC400Dict_169_0_35, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400startL",1130,G__NKNFADC400Dict_169_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400stopL",1026,G__NKNFADC400Dict_169_0_37, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_RunL",1388,G__NKNFADC400Dict_169_0_38, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400startH",1126,G__NKNFADC400Dict_169_0_39, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400stopH",1022,G__NKNFADC400Dict_169_0_40, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_RunH",1384,G__NKNFADC400Dict_169_0_41, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_RL",1304,G__NKNFADC400Dict_169_0_42, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_RL",1161,G__NKNFADC400Dict_169_0_43, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_TIMER",1388,G__NKNFADC400Dict_169_0_44, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_ENUM",1312,G__NKNFADC400Dict_169_0_45, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_TLT",1390,G__NKNFADC400Dict_169_0_46, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_TLT",1247,G__NKNFADC400Dict_169_0_47, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_TOW",1396,G__NKNFADC400Dict_169_0_48, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_TOW",1253,G__NKNFADC400Dict_169_0_49, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400enable_DCE",1410,G__NKNFADC400Dict_169_0_50, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400disable_DCE",1519,G__NKNFADC400Dict_169_0_51, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_DCE",1207,G__NKNFADC400Dict_169_0_52, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_STAT",1319,G__NKNFADC400Dict_169_0_53, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400check_CPU",1333,G__NKNFADC400Dict_169_0_54, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("waitCPU",669,G__NKNFADC400Dict_169_0_55, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400prog_FPGA",1317,G__NKNFADC400Dict_169_0_56, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400stat_FPGA",1321,G__NKNFADC400Dict_169_0_57, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400version_FPGA",1651,G__NKNFADC400Dict_169_0_58, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400prog_CPLD",1322,G__NKNFADC400Dict_169_0_59, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400stat_CPLD",1326,G__NKNFADC400Dict_169_0_60, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400version_CPLD",1656,G__NKNFADC400Dict_169_0_61, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_SN",1164,G__NKNFADC400Dict_169_0_62, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400enable_FLASH",1572,G__NKNFADC400Dict_169_0_63, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400disable_FLASH",1681,G__NKNFADC400Dict_169_0_64, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400check_FLASH",1467,G__NKNFADC400Dict_169_0_65, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400write_FLASH",1512,G__NKNFADC400Dict_169_0_66, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"b - - 0 - opcode k - - 0 - addr "
"b - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400read_FLASH",1369,G__NKNFADC400Dict_169_0_67, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - addr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400stat_FLASH",1401,G__NKNFADC400Dict_169_0_68, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400update_FPGA",1520,G__NKNFADC400Dict_169_0_69, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"C - - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400update_CPLD",1525,G__NKNFADC400Dict_169_0_70, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"C - - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NFADC400update_ALUT",1544,G__NKNFADC400Dict_169_0_71, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - devnum k - - 0 - mid "
"k - - 0 - ch C - - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__NKNFADC400Dict_169_0_72, 85, G__get_linked_tagnum(&G__NKNFADC400DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NKNFADC400::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__NKNFADC400Dict_169_0_73, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKNFADC400::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__NKNFADC400Dict_169_0_74, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NKNFADC400::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__NKNFADC400Dict_169_0_75, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NKNFADC400::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NKNFADC400DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NKNFADC400Dict_169_0_79, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NKNFADC400Dict_169_0_80, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKNFADC400::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NKNFADC400Dict_169_0_81, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKNFADC400::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__NKNFADC400Dict_169_0_82, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKNFADC400::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NKNFADC400Dict_169_0_83, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKNFADC400::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NKNFADC400", 649, G__NKNFADC400Dict_169_0_84, (int) ('i'), G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400), -1, 0, 1, 1, 1, 0, "u 'NKNFADC400' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NKNFADC400", 775, G__NKNFADC400Dict_169_0_85, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__NKNFADC400Dict_169_0_86, (int) ('u'), G__get_linked_tagnum(&G__NKNFADC400DictLN_NKNFADC400), -1, 1, 1, 1, 1, 0, "u 'NKNFADC400' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNKNFADC400Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNKNFADC400Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNKNFADC400Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NKNFADC400DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_NK6UVME = { "NK6UVME" , 99 , -1 };
G__linked_taginfo G__NKNFADC400DictLN_NKNFADC400 = { "NKNFADC400" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNKNFADC400Dict() {
  G__NKNFADC400DictLN_TClass.tagnum = -1 ;
  G__NKNFADC400DictLN_TBuffer.tagnum = -1 ;
  G__NKNFADC400DictLN_TMemberInspector.tagnum = -1 ;
  G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NKNFADC400DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__NKNFADC400DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NKNFADC400DictLN_NK6UVME.tagnum = -1 ;
  G__NKNFADC400DictLN_NKNFADC400.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNKNFADC400Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_NK6UVME);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NKNFADC400DictLN_NKNFADC400),sizeof(NKNFADC400),-1,1280,(char*)NULL,G__setup_memvarNKNFADC400,G__setup_memfuncNKNFADC400);
}
extern "C" void G__cpp_setupNKNFADC400Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNKNFADC400Dict()");
  G__set_cpp_environmentNKNFADC400Dict();
  G__cpp_setup_tagtableNKNFADC400Dict();

  G__cpp_setup_inheritanceNKNFADC400Dict();

  G__cpp_setup_typetableNKNFADC400Dict();

  G__cpp_setup_memvarNKNFADC400Dict();

  G__cpp_setup_memfuncNKNFADC400Dict();
  G__cpp_setup_globalNKNFADC400Dict();
  G__cpp_setup_funcNKNFADC400Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNKNFADC400Dict();
  return;
}
class G__cpp_setup_initNKNFADC400Dict {
  public:
    G__cpp_setup_initNKNFADC400Dict() { G__add_setup_func("NKNFADC400Dict",(G__incsetup)(&G__cpp_setupNKNFADC400Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNKNFADC400Dict() { G__remove_setup_func("NKNFADC400Dict"); }
};
G__cpp_setup_initNKNFADC400Dict G__cpp_setup_initializerNKNFADC400Dict;

